### PR TITLE
docs: migrate from api-documenter to typedoc

### PR DESCRIPTION
**Pull request by divdavem**

### CODE REVIEW

**Comment by divdavem** [comment]
Note that all relative links (including the logo) from the `README.md` file are currently not properly handled in the resulting documentation.

**Comment by divdavem** [comment]
> Note that all relative links (including the logo) from the `README.md` file are currently not properly handled in the resulting documentation.

I have now replaced relative links by absolute links to GitHub.

**Review by fbasso — APPROVED** [review]
LGTM

**Comment by divdavem** [comment]
@fbasso Thank you for your review!

**Pull request merged**
